{
 "title": "AllSensorData",
 "description": "All calibrated sensor data (gasses) from both SE and RIVM stations",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "NO2 - Nitrogen Dioxide - All Sensors - Calibrated Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Smart Emission - All Stations - NO2  + RIVM Stations",
   "type": "graph",
   "description": "Note AirSensEUR stations start with 1182* id digits. Klik op station in legenda om alleen die te zien, shift-klik v meerdere.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ug/m3" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"joserefined\" WHERE \"component\" = 'no2' AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" }
     ]
    }
   ]
  },
  {
   "title": "O3 - Ozone - All Sensors - Calibrated Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Smart Emission - All Stations - O3  + RIVM Stations",
     "type": "graph",
     "description": "Klik op station in legenda om alleen die te zien, shift-klik v meerdere.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "ug/m3" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE (\"component\" = 'o3') AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'ozone__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CO2 - Carbon Dioxide - All Sensors - Calibrated Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Smart Emission - All Stations - CO2  + RIVM Stations",
     "type": "graph",
     "description": "Klik op station in legenda om alleen die te zien, shift-klik v meerdere.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "ppm" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE (\"component\" = 'co2') AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'carbon_dioxide__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CO - Carbon Monoxide - All Sensors - Calibrated Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Smart Emission - All Stations - CO  + RIVM Stations",
     "type": "graph",
     "description": "Klik op station in legenda om alleen die te zien, shift-klik v meerdere.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "ug/m3" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE (\"component\" = 'co') AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'carbon_monoxide__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "NO - Nitrogen Oxide - All Sensors - Calibrated Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Smart Emission - All Stations - NO  + RIVM Stations",
     "type": "graph",
     "description": "NItrogen monoxide - Klik op station in legenda om alleen die te zien, shift-klik v meerdere.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "ug/m3" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE (\"component\" = 'no') AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE (\"component\" = 'nitrogen_monoxide__air_' ) AND $timeFilter GROUP BY time(1h), \"station\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Compare RIVM LML with Calibrated Jose Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "NO2 Uurwaarden - Nijmegen Graafseweg - in mg/m3",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "mg/m3" }
     ],
     "targets": [
      {
       "alias": "RIVM Station NL00741 Graafseweg",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
        { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_graafseweg" }
       ]
      },
      {
       "alias": "SE Graafseweg Station 55 Calibrated",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") AS \"value\" FROM \"joserefined\" WHERE \"component\" = 'no2' AND \"station\" = '55' AND $timeFilter GROUP BY time(1h) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" },
        { "condition": "AND", "key": "station", "operator": "=", "value": "55" }
       ]
      }
     ]
    },
    {
     "title": "NO2 Uurwaarden - Nijmegen - de Ruyterstraat - in mg/m3",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "mg/m3" }
     ],
     "targets": [
      {
       "alias": "RIVM Station NL00742 Ruyterstraat",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "station" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rivm",
       "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time(1h), \"station\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
        { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_ruyterstraat" }
       ]
      },
      {
       "alias": "SE Ruyterstraat Station 45 Calibrated",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "joserefined",
       "query": "SELECT mean(\"value\") AS \"value\" FROM \"joserefined\" WHERE \"component\" = 'no2' AND \"station\" = '55' AND $timeFilter GROUP BY time(1h) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "component", "operator": "=", "value": "no2" },
        { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
       ]
      }
     ]
    }
   ]
  }
 ]
}