{
 "title": "Calibration",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  { "title": "NO2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NO2 Hourly averages - Nijmegen Ruyterstraat (ASE_NL01 from 10.10.2018)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM Official (SOS)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_ruyterstraat" }
     ]
    },
    {
     "alias": "Jose (station 45)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '45' ) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    },
    {
     "alias": "ASE_NL_01 (station 11820001)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820001' ) AND $timeFilter AND time > '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    }
   ]
  },
  {
   "title": "NO2 Hourly averages  - Breukelen SIte (ASE_NL01-05 from 01.08.2018 - 10.10.2018)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ug/m3" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "breukelen_snelweg" }
     ]
    },
    {
     "alias": "ASE_NL01 (station 11820001)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820001' ) AND $timeFilter AND time <  '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ASE_NL02 (station 11820002)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820002' ) AND $timeFilter AND time <  '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ASE_NL03 (station 11820003)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820003' ) AND $timeFilter AND time <  '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ASE_NL04 (station 11820004)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820004' ) AND $timeFilter AND time <  '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ASE_NL05 (station 11820005)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '11820005' ) AND $timeFilter AND time <  '2018-10-10T00:00:00Z' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NO2 Uurwaarden - Nijmegen Graafseweg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_graafseweg" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'no2' AND (\"station\" = '55' OR \"station\" = '14') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "55" }
     ]
    }
   ]
  },
  {
   "title": "NO2 Uurwaarden - Utrecht Kardinaal de Jongeweg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "utrecht_de_jongweg" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "76" }
     ]
    }
   ]
  },
  {
   "title": "NO2 Uurwaarden - Utrecht Erzeijstraat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'nitrogen_dioxide__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_dioxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "utrecht_erzeijstraat" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "no2" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "78" }
     ]
    }
   ]
  },
  { "title": "NO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "NO Uurwaarden - Breukelen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'ozone__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "nitrogen_monoxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "breukelen_snelweg" }
     ]
    }
   ]
  },
  { "title": "O3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "O3 Uurwaarden - Nijmegen Ruyterstraat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'ozone__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "ozone__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_ruyterstraat" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'o3' AND (\"station\" = '45' OR \"station\" = '12') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "o3" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    },
    {
     "alias": "ASE_NL_01 (station 11820001)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'o3' AND (\"station\" = '11820001') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "o3" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    }
   ]
  },
  {
   "title": "O3 Uurwaarden - Utrecht Erzeijstraat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'ozone__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "ozone__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "utrecht_erzeijstraat" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "joserefined",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "o3" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "78" }
     ]
    }
   ]
  },
  {
   "title": "O3 Uurwaarden - Breukelen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") AS \"value\" FROM \"rivm\" WHERE \"component\" = 'ozone__air_' AND $timeFilter GROUP BY time($interval), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "ozone__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "breukelen_snelweg" }
     ]
    }
   ]
  },
  { "title": "CO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CO Uurwaarden - Nijmegen Ruyterstraat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'carbon_monoxide__air_' AND $timeFilter GROUP BY time(1h), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "carbon_monoxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_ruyterstraat" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'co' AND (\"station\" = '45' OR \"station\" = '12') AND $timeFilter GROUP BY time(1h), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "co" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    },
    {
     "alias": "ASE_NL01 (station 11820001)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'co' AND (\"station\" = '11820001') AND $timeFilter GROUP BY time(1h), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "co" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "45" }
     ]
    }
   ]
  },
  {
   "title": "CO Uurwaarden - Nijmegen Graafseweg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RIVM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "rivm",
     "query": "SELECT mean(\"value\") FROM \"rivm\" WHERE \"component\" = 'carbon_monoxide__air_' AND $timeFilter GROUP BY time(1h), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "carbon_monoxide__air_" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "nijmegen_graafseweg" }
     ]
    },
    {
     "alias": "Jose",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "station" ], "type": "tag" }
     ],
     "measurement": "joserefined",
     "query": "SELECT mean(\"value\") FROM \"joserefined\" WHERE \"component\" = 'co' AND (\"station\" = '55' OR \"station\" = '14') AND $timeFilter GROUP BY time(1h), \"station\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "component", "operator": "=", "value": "co" },
      { "condition": "AND", "key": "station", "operator": "=", "value": "55" },
      { "condition": "OR", "key": "station", "operator": "=", "value": "14" }
     ]
    }
   ]
  }
 ]
}